### ISSUE TITLE
[Problem]Stop the Line

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#10]
I meet some problem in making some effect on the line.

In fact, I just want to let the line stop at y=0.5, so I thought some idea to solve it.

Firstly, I used the PCtyx function, turned the line to "Frz". The line stoped, but when I export as C2 level and run it on Cytoid, I found that the line will never stop until the line go to the end of page.

Next, I try to change the bpm to 12800, the line stoped in PCtyx, But when I try to play it on Cytoid, it didn't work.

Finally, I try to change the the bpm down to 0.1,like this:
![image](https://user-images.githubusercontent.com/39217423/77900398-8cc8c580-72b0-11ea-851e-2c2f265ed159.png)

However, when it take effect, the fact is different form what I expected.
![image](https://user-images.githubusercontent.com/39217423/77900639-ed580280-72b0-11ea-8920-bcb8a9fbe1a6.png)

**Comment by XionUzuki** [comment]
Not an issue and an intended behavior of c2 export; It is clearly written in the [doc ](https://docs.google.com/document/d/1BhSrt75mdEBCJfKPf5B2WlgmuBRJ6WmWviH95-x4Sqk/edit#) that it is IMPOSSIBLE to make scanline freeze midpage for Cy2us format.

Midpage freeze is exclusive to PCtyx.

**Comment by XionUzuki** [comment]
For absurdly high/low BPM "issue", you have to use them very carefully to avoid hitting the page cap. Make it 16~32x slower/faster than usual bpm is enough.

**Comment by Teages** [comment]
> Not an issue and an intended behavior of c2 export; It is clearly written in the [doc ](https://docs.google.com/document/d/1BhSrt75mdEBCJfKPf5B2WlgmuBRJ6WmWviH95-x4Sqk/edit#) that it is IMPOSSIBLE to make scanline freeze midpage for Cy2us format.
> 
> Midpage freeze is exclusive to PCtyx.

Emmmmmm

Thanks for your quickly reply. But it seems that some way can stop the line, like this:

![stop_the_line_zip](https://user-images.githubusercontent.com/39217423/77920149-ada11300-72d0-11ea-8d53-8062053548f2.gif)

BTW, may I translate the doc to Chinese to help Chinese Charter master how to use PCtyx_v200?

**Comment by XionUzuki** [comment]
The way midpage "Freeze" scanline is handled in C2 actually using a very slow bpm to make it slowly move in the middle and resume it in a very complicated calculations, making it looks like it freezes for a moment.

**Comment by XionUzuki** [comment]
As for the translation, 可以啊。

**Comment by Teages** [comment]
> The way midpage "Freeze" scanline is handled in C2 actually using a very slow bpm to make it slowly move in the middle and resume it in a very complicated calculations, making it looks like it freezes for a moment.

I realized it, so I tryed it.
![image](https://user-images.githubusercontent.com/39217423/77923861-99134980-72d5-11ea-853c-2cf0bbe29c37.png)
but the two "setings" note have merge to one, and I found it:
![image](https://user-images.githubusercontent.com/39217423/77924606-7170b100-72d6-11ea-9912-20ed19d65763.png)
It seems that my line-stoper have been merge as one because of it.

BTW, "可以啊" is speaking Chinese, 请问您是否掌握汉语?

**Comment by XionUzuki** [comment]
The 0.1 bpm "issue" , as I said:

> 
> 
> For absurdly high/low BPM "issue", you have to use them very carefully to avoid hitting the page cap. Make it 16~32x slower/faster than usual bpm is enough.

The reason the 2nd scanline is erased is because it goes beyond the page cap; It has nothing to do with the C2 export fixes. 

Look at the music slider and it goes beyond your music's duration, the 0.25 gap between those 2 scanlines * 0.1 bpm is 300 seconds, which is clearly too big and it goes beyond your music's duration. There's a Y parameter to let you manually type in its Y-position for easing the purpose ou want to use a very small bpm. It's very complicated to make a midpage "Freeze" scanline for C2.

我是大馬華人，是可以說中文的哦~

**Comment by Teages** [comment]
> The 0.1 bpm "issue" , as I said:
> 
> > For absurdly high/low BPM "issue", you have to use them very carefully to avoid hitting the page cap. Make it 16~32x slower/faster than usual bpm is enough.
> 
> The reason the 2nd scanline is erased is because it goes beyond the page cap; It has nothing to do with the C2 export fixes.
> 
> Look at the music slider and it goes beyond your music's duration, the 0.25 gap between those 2 scanlines * 0.1 bpm is 300 seconds, which is clearly too big and it goes beyond your music's duration. There's a Y parameter to let you manually type in its Y-position for easing the purpose ou want to use a very small bpm. It's very complicated to make a "Freeze" scanline for C2.
> 
> 我是大馬華人，是可以說中文的哦~

呜,原来和EK大大一样,早知道就不用蹩脚的英语了.

感谢您的解答,不知道您是否愿意进大陆的Cy谱师交流群呢qaq

这是官方第一届CCC的QQ群号:885165145 ,如果您对大陆Cy自制圈感兴趣可以进群找管理员(就下图那个Tix,著名贵阳王)标明身份进谱师群.
![image](https://user-images.githubusercontent.com/39217423/77930550-9b79a180-72dd-11ea-8466-14a7dd738743.png)

**Comment by Teages** [comment]
> The 0.1 bpm "issue" , as I said:
> 
> > For absurdly high/low BPM "issue", you have to use them very carefully to avoid hitting the page cap. Make it 16~32x slower/faster than usual bpm is enough.
> 
> The reason the 2nd scanline is erased is because it goes beyond the page cap; It has nothing to do with the C2 export fixes.
> 
> Look at the music slider and it goes beyond your music's duration, the 0.25 gap between those 2 scanlines * 0.1 bpm is 300 seconds, which is clearly too big and it goes beyond your music's duration. There's a Y parameter to let you manually type in its Y-position for easing the purpose ou want to use a very small bpm. It's very complicated to make a midpage "Freeze" scanline for C2.
> 
> 我是大馬華人，是可以說中文的哦~

I asked another charter for some information about how to stop the scanline on the middle of the screen.

1. unoffical way: Change `"scan_line_direction"` to `0`

![image](https://user-images.githubusercontent.com/39217423/78097894-25c22280-7410-11ea-96c3-640edd7cbb4c.png)
 
2. offical way: Used in V.(a double hold,the scanline stoped and then move quickly), use BPM0.1 and then use BPM9999

The way 1 can stop at middle,and the way 2 can stop at every where.

Here is the chat screenshot.

![2020-3-31_20-18-38](https://user-images.githubusercontent.com/39217423/78097725-93ba1a00-740f-11ea-8212-7db51719d502.PNG)

Maybe it is unnecessery, but I hope it could be add in the next main update.

**Comment by XionUzuki** [comment]
因为QQ在国外创账号成为最大的问题 太多的不便让我完全不能使用QQ 恐怕我无法上QQ群了解并跟使用群们沟通，抱歉了。以后有任何问题可欢迎使用中文在此询问/报告。任何有优化操作与UI的意见也可以。

至于要把扫描线停在正中央的方案1我会考虑。目前要在C2实现如Rnk0u大大所说扫描线停在偏中间某些位置只能使用的方案2进行：复杂的BPM算术。这是我的公式（在此声明并没测试过，会有误算），套用予扫描线在中间“停止”片刻后，就恢复到原本的状态。在之前先把所有在那个扫描线时间点的拍点都先放好。

1）这个扫描线大概“停”多少屏 = P
2）把P乘予某数值让它变成至少32倍慢 = N
3）将这个要“停”的扫描线（A）的速度放 BPM ÷ N 
4）放另一个扫描线（B）放在（A）之后的时间点，它的Y位置 等于 P÷N +（A）的Y位置
5） （B）的速度BPM × N ÷ P
6）将最后个扫描线（C）放到屏尾边，BPM就放回原本的
7）Re-Sync 确定模式设定为Time后 进行套用

**Comment by Teages** [comment]
> 因为QQ在国外创账号成为最大的问题 太多的不便让我完全不能使用QQ 恐怕我无法上QQ群了解并跟使用群们沟通，抱歉了。以后有任何问题可欢迎使用中文在此询问/报告。任何有优化操作与UI的意见也可以。
> 
> 至于要把扫描线停在正中央的方案1我会考虑。目前要在C2实现如Rnk0u大大所说扫描线停在偏中间某些位置只能使用的方案2进行：复杂的BPM算术。这是我的公式（在此声明并没测试过，会有误算），套用予扫描线在中间“停止”片刻后，就恢复到原本的状态。在之前先把所有在那个扫描线时间点的拍点都先放好。
> 
> 1）这个扫描线大概“停”多少屏 = P
> 2）把P乘予某数值让它变成至少32倍慢 = N
> 3）将这个要“停”的扫描线（A）的速度放 BPM ÷ N
> 4）放另一个扫描线（B）放在（A）之后的时间点，它的Y位置 等于 P÷N +（A）的Y位置
> 5） （B）的速度BPM × N ÷ P
> 6）将最后个扫描线（C）放到屏尾边，BPM就放回原本的
> 7）Re-Sync 确定模式设定为Time后 进行套用

参考了一下您的方案, 我自己也想了一套方案

![image](https://user-images.githubusercontent.com/39217423/78266142-f3134980-7537-11ea-8328-92a643f63326.png)


1. 起始点放一个Scanline_Start, 速度为`BPM*15 / (16*16)`
2. 结束点放一个Scanline_End, 速度为`BPM`
3. 取起始点和结束点连线的`16分`点, 放一个Scanline_jump, 速度为`BPM*16` 
4. enjoy!

实验结果: 大成功!!!!!

唯一的遗憾是Cytoid1.5把线速平均掉了,游玩正常但是停线特效美丽(悲)

不过在Cytoid2.0alpha5下视觉效果震撼!!!

> 2020.3.4补充

实验成功了,但是实践出了一点小问题(

实验又成功了
1. 起始点放一个Scanline_Start, 速度为`BPM/15`
2. 结束点放一个Scanline_End, 速度为`BPM`
3. 取起始点和结束点连线的`16分`点, 放一个Scanline_jump, 速度为`BPM*15` 
4. enjoy again!

但是PCtyx显示似乎有点问题,似乎是因为BPM骤变,希望能调整出现速度跟上一页的**平均BPM**挂钩.

**Comment by XionUzuki** [comment]
Cytoid的相关问题请到Cytoid的作者的Git页面提出相关报告。谢谢。

请再详细阐述PCtyx“显示”问题。

**Comment by Teages** [comment]
> Cytoid的相关问题请到Cytoid的作者的Git页面提出相关报告。谢谢。
> 
> 请再详细阐述PCtyx“显示”问题。

这个问题有点难以阐述,我举个例子

我依照上面第二条实验的公式,设置的也头停线,页尾恢复原速度,形成在页头停线,随后突然跳到页尾的效果.然后我在下一页的页头放了一个note

但在PCtyx中预览的时候,这个note的出现动画非常之快,以至于只能看到一个判定反馈,希望能给note的出现动画设置一个**上限速度**

> 此外, 对于PCtyx文档的翻译已经完成[PCtyx_Editor_CN.pdf](https://blog.teages.xyz/posts-source/newPCtyx/PCtyx_Editor_CN.pdf),指南的一部分内容(Compose模式相关有一句,我的理解是`点击键盘左边的按键会在左边出现note反馈,右边同理`,还有SKIN相关,因为我没有制作note皮肤的能力,而且默认皮肤例子不全,我无法进行猜测,因此保留了一些原文)
>
> ~~此外,我还打了个教程广告~~
>
> 根据这篇文档, 我结合之前的实践写了一篇教程 [PCtyx入门指南](https://blog.teages.xyz/pages/newPCtyx.html)
>
> 教程和文档翻译可能存在错误, 如果有问题请在文章评论区指正, 我会尽快更新

**Comment by XionUzuki** [comment]
之后的版本会添加AR能调整各个note的出现速度。敬请期待。

辛苦您的PCtyx文档的翻译了。SKIN的完整版本我会在发出下一个版本时顺便附上。要注意PCtyx的原文档也会常更新以反映未来版本所做的改变哦。

未来的版本稍微优化了一些控制与改变：
- 滑鼠中键拉大蓝框选择note => 在选择/移动note模式下右键
- 滑鼠必须标在被选择的note上，滑鼠滚动上/下或按QWEASD键改变被选择的note 位置、链接ID、hold长度 => 只要有至少一个note被选，滑鼠标在格线范围内即可操作。
- 0为开始的页数编号更改为1，也将“不能在第0页放note”限制移除。
- 链接ID上限8改为16

**Comment by Teages** [comment]
> 之后的版本会添加AR能调整各个note的出现速度。敬请期待。
> 
> 辛苦您的PCtyx文档的翻译了。SKIN的完整版本我会在发出下一个版本时顺便附上。要注意PCtyx的原文档也会常更新以反映未来版本所做的改变哦。
> 
> 未来的版本稍微优化了一些控制与改变：
> 
> * 滑鼠中键拉大蓝框选择note => 在选择/移动note模式下右键
> * 滑鼠必须标在被选择的note上，滑鼠滚动上/下或按QWEASD键改变被选择的note 位置、链接ID、hold长度 => 只要有至少一个note被选，滑鼠标在格线范围内即可操作。
> * 0为开始的页数编号更改为1，也将“不能在第0页放note”限制移除。
> * 链接ID上限8改为16

好的,由于目前学业原因,如果没有影响到正常使用的重大错误,翻译的更新可能会延迟几个星期,在几周(十几周?)我毕业后会及时追上

另外,这个`滑鼠中键拉大蓝框选择note => 在选择/移动note模式下右键`的功能好像没有在文档提到...

> 不过好像之前更新日志有说到

这个issuse越来越难翻了,先关掉了(
