### ISSUE TITLE
[Bug report]偶尔出现音频延迟

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#11]
据多位谱师反馈, 在预览的时候**很容易**出现音频播放延迟的问题.

经过测试, 概率约30%

环境: Windows 1909 & Ubuntu 18.04

版本V200.5

**Comment by Teages** [comment]
虽然重新开始预览可以解决延迟问题, 但很多新谱师为此感到困惑, 写出很多错音

**Comment by XionUzuki** [comment]
很可惜此情况并不在我可以修复的范围。唯一的方法是更新声卡驱动。如果有其他比较吃记忆体的程式在运作中（尤其是火狐或Google Chrome），请将它们关闭。

**Comment by Teages** [comment]
似乎和记忆体无关, 我的笔记本是典型的内存过剩(一般只能用75%)

![image](https://user-images.githubusercontent.com/39217423/78566013-3d0a7100-7851-11ea-9024-a4701cc8a546.png)

不过我已经想到了如何让新手们调整的办法, 所以这个问题现在影响不大.

非常感谢您的回复.

**Comment by Teages** [comment]
发现一个规律, 这个问题常常出现在许久没有预览之后的第一次预览. 如果我连开两次预览就不会有这种问题, 或许这个例子可以找出问题根源?

@XionUzuki

**Comment by Teages** [comment]
V201更新以后, 经过多次尝试复现问题, 这种情况不再出现
