### ISSUE TITLE
[Bug report]Ctrl+A选中全部note时会将hold加长一格

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#12]
如图所示:
![image](https://user-images.githubusercontent.com/39217423/78572551-346a6880-785a-11ea-922a-99cf1efaf180.png)

![image](https://user-images.githubusercontent.com/39217423/78572579-3d5b3a00-785a-11ea-9057-91b40ce1109a.png)

**Comment by XionUzuki** [comment]
已知bug并修复于下一个版本。

**Comment by XionUzuki** [comment]
v201已修復此問題
