### ISSUE TITLE
[Bug report]调整BPM以后note错位/跳页

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#13]
调整BPM以后, 在某些页里,存在下面的情况:

- 原本在页头的note会跑到上一页页尾, 
- 某些hold的长度会异常增加0.0014.
- 有些hold虽然显示正常,但它们实际长度异常, 会被PCtyx处理为Long Hold

更为严重的是, 这发生在调整BPM位置的前面, 例如我调整了第20页的BPM, 但是我在5,9,13页都发现了这些情况. 当时我的设置是根据时间同步, 保留之后的scanline.

我的习惯是做到要变速的那一页才变速, 所以不清楚后面的页数是否存在错位bug

**Comment by XionUzuki** [comment]
这是电脑计算偏差问题 页头的note会因此很容易跑到页尾，hold也会难免有偏差。
修复也太过于麻烦 所以也跟scanline会偏移的情况下不修复
跑到页尾的note可以使用WS移动让它们跑回页头，请自行修复

**Comment by Teages** [comment]
> 这是电脑计算偏差问题 页头的note会因此很容易跑到页尾，hold也会难免有偏差。
> 修复也太过于麻烦 所以也跟scanline会偏移的情况下不修复
> 跑到页尾的note可以使用WS移动让它们跑回页头，请自行修复

但是影响到scanline这个note对应时间之前的note了，理应不会影响前面的note的

**Comment by XionUzuki** [comment]
201版本应该修复了re-sync会调整整个谱面的note的问题 
此问题会持续留意中

**Comment by Teages** [comment]
> 201版本应该修复了re-sync会调整整个谱面的note的问题
> 此问题会持续留意中

新情况: 一名谱师,使用BPM155, 设置了offset, 存在每次保存都会导致note位置偏移0.002的问题

**Comment by XionUzuki** [comment]
> 新情况: 一名谱师,使用BPM155, 设置了offset, 存在每次保存都会导致note位置偏移0.002的问题

请再次详细描述。是设置了什么offset？是scanline的开头时间？还是re-sync设置？re-sync设置是时间？

**Comment by Teages** [comment]
应该是开头Scanline的offset, 原文如下

![Screenshot_20200412-193213457](https://user-images.githubusercontent.com/39217423/79067790-84cb4580-7cf4-11ea-8669-20c9449ae44f.jpg)

**Comment by XionUzuki** [comment]
我前提所说的，计算偏差问题，也是修复最不可能的一点。scanline的开头时间并不是跟offset数值一样的。还有，调整开头时间后如果re-sync是时间的话，note也会跟着新的扫描线时间点做出调整。re-sync也说明了note会偏移。

建议把扫描线都提前摆放好后再做谱。

**Comment by Teages** [comment]
> 我前提所说的，计算偏差问题，也是修复最不可能的一点。scanline的开头时间并不是跟offset数值一样的。还有，调整开头时间后如果re-sync是时间的话，note也会跟着新的扫描线时间点做出调整。建议把扫描线都提前

他的意思好像不是调整了Scanline导致的note偏移, 而是保存会导致note偏移.
![image](https://user-images.githubusercontent.com/39217423/79068172-7e8a9880-7cf7-11ea-98e5-506cc7ec0b1a.png)
![image](https://user-images.githubusercontent.com/39217423/79068181-92ce9580-7cf7-11ea-8a18-526670e368d0.png)
![image](https://user-images.githubusercontent.com/39217423/79068185-a548cf00-7cf7-11ea-89aa-ae0898951006.png)
![image](https://user-images.githubusercontent.com/39217423/79068190-ad087380-7cf7-11ea-9879-59499c36b9fa.png)

**Comment by XionUzuki** [comment]
使用者所说的保存是指一直去re-sync按apply吗？如果有的话偏移也会是必然的。

**Comment by XionUzuki** [comment]
还有，我只接受最新版本可以生成的bug report哦。

**Comment by Teages** [comment]
> 使用者所说的保存是指一直去re-sync按apply吗？如果有的话偏移也会是必然的。

是指保存谱面, 不过这个bug我没遇到过
