### ISSUE TITLE
[Bug report]Ctrl + A会导致无法正确吸附到网格线

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#14]
![image](https://user-images.githubusercontent.com/39217423/79064385-07dfa200-7cdb-11ea-81d3-0862a8f2b928.png)

当我使用`Ctrl + A`选中全部, 并尝试上下移动note时, Note不能正确被吸附到网格上

**Comment by XionUzuki** [comment]
已纳入下一个更新的修复名单。

**Comment by XionUzuki** [comment]
v201.1热修已修复此bug
