### ISSUE TITLE
[Serious bug]v201无法正确导出来自v200.5的谱面

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#16]
如题, 我尝试进行了多次转换, 但是出现了同样的错误. 导出以后一团糟.

所以我正在尝试用Excel手动降低csv谱面版本.

[相关文件](https://mega.nz/folder/Zp9zWCoI#mjxxut30reS2HMoX5gEHzA)

**Comment by XionUzuki** [comment]
先声明我目前还无法使用cytoidplayer或Cytus 2 相关的播放器实验，而且不知道cytoidplayer的相关错误。我也尚在学习c2格式相关，请包涵。
侥幸的是我已找出问题所在，再次检查了txt导出谱面相关項目发现是tempo_list中的处理方式有错误导致输出跟csv谱面内有异常的情况。目前已修复并列入下一个更新的修复名单。

請勿手動更改csv谱面版本数值以免造成更多问题。

**Comment by Teages** [comment]
> 先声明我目前还无法使用cytoidplayer或Cytus 2 相关的播放器实验，而且不知道cytoidplayer的相关错误。我也尚在学习c2格式相关，请包涵。
> 侥幸的是我已找出问题所在，再次检查了txt导出谱面相关項目发现是tempo_list中的处理方式有错误导致输出跟csv谱面内有异常的情况。目前已修复并列入下一个更新的修复名单。
> 
> 請勿手動更改csv谱面版本数值以免造成更多问题。

手动降级了一下, 在200.5导出了.

降级方法: 

1. 删除 f 以及下面的整行
2. 将 b 行数值全部减`1`(使用Excel的选择性粘贴)(还好我计算机课认真听了)

好在我只是对谱面的一些note进行了x轴的调整, 进行对照反推了升级内容.

使用Excel修改CSV可以做到大规模的处理.例如最近CytoidIO上的新谱面`Nearly 10,000 notes`,就是用Excel公式+自动填充制作的.(只要懂得CSV代表的内容)

> ~~不过这个`Nearly 10,000 notes`的制作用的还是PCtyx131版本,因为PCtyx200.5加载15min的音频就撑不住了~~

当然, 只要有备份就可以随便浪了(X)
