### ISSUE TITLE
[serious bug]导出问题

### ISSUE THREAD

**Issue by xlj633** [XionUzuki/PCtyx#17]
当在v201完整写完一个谱面的时候会遇到如下问题
1：开始的bpm变为二分之一了
2：当修改txt将bpm变回正常的时候谱面与音乐相差了整整一屏
顺便问一下AR的设定限制能不能接触，当写一些特效类谱面的时候，4显然达不到效果，或者说最高就是4了 
[7th.txt](https://github.com/XionUzuki/PCtyx/files/4468340/7th.txt)
附上修改过后的txt
修改了初始bpm
原来value是双倍
修改了music_offset(似乎并没有用）

**Comment by XionUzuki** [comment]
请明确的说出来。

**Comment by XionUzuki** [comment]
问题1与2同样 #16 处理 没有csv谱面与原本txt比对 这个非完整的问题我不能着手。

至于在导出与csv的AR上限我可以改，但PCtyx的播放器上限还是会把最大上限达到3.72倍左右，会跟Cytoid的完全不一致，是因为PCtyx有Grouped和None模式而且使用了比较特殊的动态时钟作播放（未清楚Cytoid跟Cytus2的播放器是否还是运用了老旧的秒时间计算法）。

**Comment by xlj633** [comment]
[问题文件打包.zip](https://github.com/XionUzuki/PCtyx/files/4468929/default.zip)
由于GitHub不支持CSV文件上传，劳您自行解压，谢谢

**Comment by xlj633** [comment]
呃，忘了说了，这里的csv与txt文件全部没有做过任何修改

**Comment by XionUzuki** [comment]
下次有任何问题您可以使用MEGA或是google drive这些云网盘平台上传哦。

经过比对调查后，由 #16  所说果然是原本导出的tempo_list是有错误导致第二个变速发生在第0个tick了。这也导致了情况1链接到2。现已修复于下一个更新版。

**Comment by xlj633** [comment]
我不会用（悲）
下一个版本希望能快点更新，因为这样几乎无法写出任何一个正常谱面
