### ISSUE TITLE
[Bug report]导出问题

### ISSUE THREAD

**Issue by xlj633** [XionUzuki/PCtyx#18]
在Pctyx中对音没问题，导出的谱面到游戏后谱面会慢一屏，会不会是pctyx中音乐快了一屏？

**Comment by Teages** [comment]
我这边没有遇到这样子的问题, 会不会是你的全局偏移量没有调好?

请使用官方谱面进行一次校准,[点击下载官方谱面 - Ecstatic](https://cytoid.io/levels/io.cytoid.ecstatic).

能否打包音频和csv谱面进zip压缩包, 并发送出来?

这样作者可以更好地定位问题.

**Comment by xlj633** [comment]
> 
> 
> 我这边没有遇到这样子的问题, 会不会是你的全局偏移量没有调好?
> 
> 请使用官方谱面进行一次校准,[点击下载官方谱面 - Ecstatic](https://cytoid.io/levels/io.cytoid.ecstatic).
> 
> 能否打包音频和csv谱面进zip压缩包, 并发送出来?
> 
> 这样作者可以更好地定位问题.

应该不是全局偏移的问题，因为我分别导入进了ctd和c2previewer，都是出现正好音乐快一屏的情况，而且没有在pctyx中调整过offset。

**Comment by xlj633** [comment]
[问题文件.zip](https://github.com/XionUzuki/PCtyx/files/4502005/default.zip)
附上音乐与谱面文件

**Comment by XionUzuki** [comment]
游戏和ctd是指cytoid吗？如果是的话我可要再次待入观察。C2previewer有快了一屏是必然是因为导出文件内有cytoid专用的music_offset，请自行在音频文件内添加静音等于导出文件内music_offset所写的时间。
