### ISSUE TITLE
[功能增强]请求加强防叠键预览

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#19]
目前, PCtyx的防叠键似乎并不够用.

例如, 在BPM180下, PCtyx不会显示上一页里y=0.5的note, 但是实际上, 这个位置仍然会引发叠键相关的问题.

改进建议: 
1. 可调整范围
2. **推荐** 直接采用"渐入"的方式处理, 线性调整上一页note的透明度. 例如: 上一页y=1的note,其不透明度是100%; 而上一页y=0的note, 其不透明度是10%

另外, 目前的计算方式似乎是直接按时间算? 更换了新的默认ar以后,似乎这个时间的算法就不太适用了...

**Comment by XionUzuki** [comment]
目前的测量上一页note因为范围太小而且没考量该屏的线速越快显示量越多。将会同时用两个方案进行调整。
