### ISSUE TITLE
【Bug report?】关于超高线速

### ISSUE THREAD

**Issue by xlj633** [XionUzuki/PCtyx#20]
在超高线速下(如100000）在pctyx的预览中不正确。
如我在200的线速下放了一个长3屏的hold
然后将第二屏线速设置为100000
在第三屏改回200
这个hold会提前结束且改回线速后第三屏起始点会发生偏移
但在ctd和c2p中没有出现问题
在制作判定线特效显得尤为不方便，希望能加以修复
也许这不是个bug？）
还有一条，能不能加快或移除预览时线展开动画（

**Comment by XionUzuki** [comment]
当线速在0.017秒以下时扫描线在pctyx会视作为停止，但可能导致hold会有些误判。之后会做出观察。

如果有csv跟音频文件 会更加方便做出调查（建议使用云端上传）

**Comment by xlj633** [comment]
实际上主要问题不是hold而是错位

**Comment by XionUzuki** [comment]
经过一些收集的报告后 这是游戏引擎不能引发少于1/60秒的tick 没有方法能修复

建议使用3600以下的线速。对于200BPM使用16倍的线速已足够。

**Comment by Teages** [comment]
> 经过一些收集的报告后 这是游戏引擎不能引发少于1/60秒的tick 没有方法能修复
> 
> 建议使用3600以下的线速。对于200BPM使用16倍的线速已足够。

所以我之前的"闪线"方案根本没有问题嘛, 那个方案是十六分之一BPM拖延时间再BPM9999来矫正判定线, 按理y轴没错那就没问题----但是实际上预览时线会多跑一段距离, 听音效却又没问题.

能否取巧: 针对这一段内容, 单独用别的方式渲染.

不过这**不是**必需的, 至少目前看来, 这个方法仅仅导致了渲染问题, 对于做谱**没有影响**.

* 或许可以向scirra反映这个问题, 考虑到Construct 2即将被停止支持, 这个想法恐怕**不切实际**.

**Comment by XionUzuki** [comment]
我倒可以使用另一个方案使用回150版本之前都用实际时钟特别处理部分“闪速”的谱面，它们似乎不会受到引擎tick的影响。但这个可能要花很长时间重新实装。

**Comment by Teages** [comment]
没关系, 这种技巧非常危险, 能合理使用的范围实在是太小了.

至少我捣鼓出来以后一次都没敢用....

**Comment by xlj633** [comment]
> 
> 
> 没关系, 这种技巧非常危险, 能合理使用的范围实在是太小了.
> 
> 至少我捣鼓出来以后一次都没敢用....

但是对于特效谱十分重要(起码我不会sb)
