### ISSUE TITLE
【功能建议】锁链

### ISSUE THREAD

**Issue by xlj633** [XionUzuki/PCtyx#22]
有没有可能，设置一个工具，选中一串直锁链，然后可以拖出弧度，来画出好看的葫芦（

**Comment by xlj633** [comment]
顺便一提，201.3版本中note的预览是可以调整的吗？在哪里调？

**Comment by Teages** [comment]
弄条漂亮的圆锥曲线, 取一个合理的间隔, 然后算出来就行了((((

**Comment by xlj633** [comment]
> 
> 
> 弄条漂亮的圆锥曲线, 取一个合理的间隔, 然后算出来就行了((((

麻烦，而且对于没学到相关知识的人极不友好

**Comment by Teages** [comment]
圆锥曲线用初中那条二次函数就行了

有高追求可以上椭圆和双曲线

**Comment by xlj633** [comment]
> 
> 
> 圆锥曲线用初中那条二次函数就行了
> 
> 有高追求可以上椭圆和双曲线

我还没学到bbb

**Comment by Teages** [comment]
> > 圆锥曲线用初中那条二次函数就行了
> > 有高追求可以上椭圆和双曲线
> 
> 我还没学到bbb

二次函数啊bbbbb

这个初中的诶

**Comment by xlj633** [comment]
> > > 圆锥曲线用初中那条二次函数就行了
> > > 有高追求可以上椭圆和双曲线
> > 
> > 我还没学到bbb
> 
> 二次函数啊bbbbb
> 
> 这个初中的诶

初三内容，我初二
