### ISSUE TITLE
[Bug Report]多次变速导致对齐问题

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#24]
重现: 350BPM两页, 58.333BPM一页, 循环六次, 在第三次循环的时候开始出现不对齐的现象, 但是从中间开始预览却不会不对齐 (基础BPM是175)

怀疑和[#20 ](https://github.com/XionUzuki/PCtyx/issues/20) 有关

**Comment by XionUzuki** [comment]
單憑片面之詞 沒有譜面跟音樂文件的話 我很難查找這種問題 😓

**Comment by Teages** [comment]
> 單憑片面之詞 沒有譜面跟音樂文件的話 我很難查找這種問題 😓

这个您可以跟着我所说的`350BPM两页, 58.333BPM一页, 循环六次`来重现这个问题,无需谱面文件.

因为我认为谱面和音乐文件是吻合的: 因为从中间开始播放并没有延迟问题, 只有从头开始播放才有这种问题

另外,原谱面已经改掉了,因为58.333BPM还要放满48分音符,完全是给自己挖坑(((
