### ISSUE TITLE
【改进建议】关于music_offset

### ISSUE THREAD

**Issue by xlj633** [XionUzuki/PCtyx#25]
我认为自动在音频前添加一整屏的offset是没有必要的，能够理解是为了给scanline留空，但是这样也会造成一些新人谱师不理解放到c2p里会慢一屏，同时剪两份曲子也是十分不方便，建议改为可以选是否添加一屏的offset。

**Comment by XionUzuki** [comment]
增添offset是為cytoid相容性與國際群的要求而定制。關於offset在非cytoid的方面在指南已說明。

只能要求c2p作者把start_offset_time變成有用的數據，或是容納cytoid專用的music_offset。

**Comment by Teages** [comment]
music_offset就是因为Scanline的初始行为不能确定而设置的,没有这个offset,做谱前的准备工作会大量增加.

另外, PCtyx的UI很棒, 建议劝说他们用这个录(?)

**Comment by Teages** [comment]
问题被关闭后的补充: fujao已在C2P(Cytus2Player)中添加了对`music_offset`的支持, 至此, 除C2U外的全部Cy系自制软件都支持`music_offset`参数.
