### ISSUE TITLE
我想帮助PCtyx使其变得更好

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [XionUzuki/PCtyx#31]
不过作者有考虑过开源吗？

**Comment by XionUzuki** [comment]
有哦 但因為這個是使用很老舊的遊戲製作器Construct 2來製作 要開源會有些難度

**Comment by WOSHIZHAZHA120** [comment]
@XionUzuki  哦这样啊
本来我是想多个谱面打包器和自动保存的
到时候我去研究一下construct 2怎么用吧

**Comment by WOSHIZHAZHA120** [comment]
> 有哦 但因為這個是使用很老舊的遊戲製作器Construct 2來製作 要開源會有些難度

左上角file可以save as project和save in one file的
保存为project然后丢到这里(?)

**Comment by XionUzuki** [comment]
我說過了 開源會有難度 不能只丟project那麼簡單 
尤其是跟其他人共享大批量更改過的event block的偏碼會很麻煩 需用註解（quote）標示更改並呈現整個.capx
PCtyx使用了批量的第三方插件和被修改過的官方音频與視頻插件 需要點時間做出整理標明出處
