### ISSUE TITLE
[Bug report]storyboard导出错误

### ISSUE THREAD

**Issue by xlj633** [XionUzuki/PCtyx#32]
在我写谱的时候，写了两屏的卡顿线特效，但是第二屏却变成了fall。
附上文件
[life flashed before weeb eyes.zip](https://github.com/XionUzuki/PCtyx/files/5179120/life.flashed.before.weeb.eyes.zip)

**Comment by XionUzuki** [comment]
更新：感謝您提供的匯報。已發現問題所在：是sb被導出時Bottom/Freeze的掃描線被誤認為Bottom/Fall。

此bug已修復於下一個的版本。
