### ISSUE TITLE
【改进建议】关于“fall”

### ISSUE THREAD

**Issue by xlj633** [XionUzuki/PCtyx#33]
在我写完下落谱后，我发现hold都只剩下头，经过初步排查我发现，当我使用fall的时候，谱面文件的该屏会被修改为静止扫描线，并且使用sb达到下落效果，但是由于原铺面中扫线已经静止，导致hold只剩下头。
建议：在使用fall的时候不动原谱，只用sb。然后在note_controller可以在fall时加一行`"style":2`，这样可以让hold达到最真实的下落效果

**Comment by xlj633** [comment]
另外，在导出sb时建议将导出的sb直接命名为storyboard.json这样就可以直接打包了，否则还需要自己改名或者修改level.json

**Comment by Teages** [comment]
> 另外，在导出sb时建议将导出的sb直接命名为storyboard.json这样就可以直接打包了，否则还需要自己改名或者修改level.json

投反对票, 这样不利于谱面版本管理

**Comment by Teages** [comment]
另外, 建议导出时使用swp作为扫线模式, 而不是不动原谱, 否则note颜色显示会错误
