### ISSUE TITLE
Hold abnormally converted to Long Hold.

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#4]
Hold abnormally converted to Long Hold.

The hold should be short hold.But it's show as a long hold when preview.

Here is a video.You can compared the Cytoid one with the two PCtyx ones.

[Download here](https://mega.nz/#F!skMhAQIB!E1A6iCIm9e64BN2pdwcBxw)

**Comment by XionUzuki** [comment]
This is more of a number rounding issue. Won't fix. The way to fix it is either nudge the note down or decrease the hold length
