### ISSUE TITLE
Cy2 export problem.

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#5]
Thanks to your great work.But here is a problem with it.

The video "Cy2-export-problem.mp4" can tell you where is the problem.

[Download video here](https://mega.nz/#F!skMhAQIB!E1A6iCIm9e64BN2pdwcBxw)

BTW,Here is only 3 bugs on v200.If these are solved,maybe it can be on stable.

**Comment by XionUzuki** [comment]
Duplicate

**Comment by XionUzuki** [comment]
#3
