### ISSUE TITLE
Audio play delay

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#7]
If the next page's BPM is not as this page's. Review form this page will couse audio play delay.

**Comment by Teages** [comment]
It also can found in 131.02a. @XionUzuki

**Comment by XionUzuki** [comment]
Issue is too vague and could not be reproduced with the provided files. More likely a hardware issues.

**Comment by Teages** [comment]
> Issue is too vague and could not be reproduced with the provided files. More likely a hardware issues.

NOT a hardware issues,I promise. Because another chacter also found this problem, and I think it is a logical problem.

Let me try to explain the problem again.

For example, now our bpm is 380 in page 30 . But in next page (31), I set 190. Now I play the review from page 30. However, the audio play later than the chart.

In my charter, you can find this example. (Not in 30, the number is I made up to explain the problem.)

 Thanks for your great work. But I think this needs to be reconsidered. @XionUzuki
