### ISSUE TITLE
A small mapping error

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#8]
![image](https://user-images.githubusercontent.com/39217423/76679831-9a2e5080-661e-11ea-84cf-5dd85c0ce06e.png)
?

**Comment by Teages** [comment]
May be not a mapping error,

But "W S" and "A D" should be reversed, I think. @XionUzuki

**Comment by Teages** [comment]
BTW, a new release should be release again **even** it just have been changed a little, for users who watching it can get the new update notice on time.

**Comment by XionUzuki** [comment]
Fixed for the next build soon. Sorry for the inconveniences and the instabilities. m(＿＿)m
