### ISSUE TITLE
[Suggestion]Some point let PCtyx easy to use

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#9]
v200.5 is updated. But there are some Charter would not like to use the new version.

So I collect their reason:

1. It is more complicated to move a note.Before they can move the note easily just drag the notes.But now they need to click the note first.

2. ....(collecting,may be not)

**Comment by XionUzuki** [comment]
1) Not a valid issue; It's not very complicated just to click to select the note. As always, when a mechanic/controls of editor NEED to be changed, get used to it. That is a feature of multi-selecting notes.

This is not a first time Project Thrinos/PCtyx overhauled the controls, and users are often move on and get used with new additions/controls.

**Comment by Teages** [comment]
> 1. Not a valid issue; It's not very complicated just to click to select the note. As always, when a mechanic/controls of editor NEED to be changed, get used to it.

Think you for your reply. Many Chinese Charter think PCtyx is a great work,thank you again for your great work!
